services:
  db:
    container_name: ticketing-db
    image: postgres:latest
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PG_DATA: /var/lib/postgresql/data
      POSTGRES_INITDB_ARGS: --auth-host=scram-sha-256
    networks:
      - ticketing
    ports:
      - ${EXT_DB_PORT}:${INT_DB_PORT}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: on-failure

#  postgres:
#    container_name: postgres
#    image: postgres
#    environment:
#      POSTGRES_USER: admin
#      POSTGRES_PASSWORD: admin
#      PGDATA: /data/postgres
#    volumes:
#      - postgres:/data/postgres
#    ports:
#      - "5050:5432"
#    networks:
#      - postgres
#    restart: unless-stopped

#  customer:
#    image: amigoscode/customer:latest
#    container_name: customer
#    ports:
#      - "8080:8080"
#    environment:
#      - SPRING_PROFILES_ACTIVE=docker
#    networks:
#      - spring
#      - postgres

networks:
  ticketing:

volumes:
  pgdata: {}
